server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka